image: docker
services:
  - docker:dind

stages:
  - deploy
  - init_database
    
deploy:
  stage: deploy
  script:
    - cd ./dev/backend/server
    - python3 -m venv env
    - /root/env/bin/pip install -r requirements.txt
    - /root/env/bin/pip install -r requirements.in
    - /root/env/bin/python setup.py develop
    - /root/env/bin/python setup.py install
    - sudo service apache2 reload
    - chmod -R 777 /root/env/lib/python3.7/site-packages/loftes-0.0-py3.7.egg
  only:
    - master

init_database:
  stage: init_database
  script:
    - mysql < /root/db.sql"
    - /root/env/bin/initialize_loftes_db production.ini
    - /root/env/bin/fill_loftes_db production.ini
  only:
    - master
