image: docker
services:
  - docker:dind

stages:
  - deploy
  - build
  - init_database
    
deploy:
  stage: deploy
  script:
    - pwd
    - /builds/acrobatt-1/lord-of-the-trips/dev/backend/server/env/bin/pip install -r requirements.txt
    - ./dev/backend/server/env/bin/pip install -r requirements.in
    - ./dev/backend/server/env/bin/python setup.py develop
    - ./dev/backend/server/env/bin/python setup.py install
    - service apache2 reload
    - chmod -R 777 ./dev/backend/server/env/lib/python3.7/site-packages/loftes-0.0-py3.7.egg
  only:
    - master

init_database:
  stage: init_database
  script:
    - mysql < /root/db.sql"
    - ./dev/backend/server/env/bin/initialize_loftes_db production.ini
    - ./dev/backend/server/env/bin/fill_loftes_db production.ini
  only:
    - master
