image: docker
services:
  - docker:dind

stages:
  - deploy
  - init_database
    
deploy:
  stage: deploy
  script:
    - cd ./dev/backend/server
    - ./env/bin/pip install -r requirements.txt
    - ./env/bin/pip install -r requirements.in
    - ./env/bin/python setup.py develop
    - ./env/bin/python setup.py install
    - sudo service apache2 reload
    - cp /production.ini .

  only:
    - master

variables:
  GIT_CLEAN_FLAGS: -x -f -e dev/backend/server/env/
