image: docker
services:
  - docker:dind

stages:
  - deploy
  - init_database
    
deploy:
  stage: deploy
  script:
    - sudo apt purge python3-venv python3-pip -y
    - sudo apt install python3.7-venv python3.7-pip -y
    - cd ./dev/backend/server
    - python3.7 -m venv env
    - ./env/bin/pip install -r requirements.txt
    - ./env/bin/pip install -r requirements.in
    - ./env/bin/python setup.py develop
    - ./env/bin/python setup.py install
    - sudo service apache2 reload
    - chmod -R 777 env/lib/python3.7/site-packages/loftes-0.0-py3.7.egg
    - mysql < /root/db.sql"
    - sudo ./env/bin/initialize_loftes_db production.ini
    - sudo ./env/bin/fill_loftes_db production.ini
  only:
    - master
