define({
  "name": "Lord of the Trips",
  "version": "0.1.0",
  "description": "apiDoc basic example",
  "title": "LOFTS - API documentatiton",
  "url": "https://hephaistos.nathanaelderousseaux.fr/api",
  "sampleUrl": "https://hephaistos.nathanaelderousseaux.fr/api",
  "order": [
    "Login",
    "SignUp",
    "Whoami",
    "GetChallenges",
    "PostChallenge",
    "GetChallenge",
    "PutChallenge",
    "PatchChallenge",
    "DeleteChallenge",
    "VerifyChallenge",
    "GetChallengeImage",
    "PostChallengeImage",
    "GetCrossingPoints",
    "PostCrossingPoint",
    "GetCrossingPoint",
    "PutCrossingPoint",
    "PatchCrossingPoint",
    "DeleteCrossingPoint",
    "GetSegments",
    "PostSegment",
    "GetSegment",
    "PutSegment",
    "PatchSegment",
    "DeleteSegment",
    "GetEvents",
    "PostEvent",
    "GetEvent",
    "GetObstaclesByChallenge",
    "GetObstaclesBySegment",
    "PostObstacle",
    "GetObstacle",
    "PutObstacle",
    "PatchObstacle"
  ],
  "defaultVersion": "0.0.0",
  "apidoc": "0.3.0",
  "generator": {
    "name": "apidoc",
    "time": "2021-05-24T17:10:51.316Z",
    "url": "https://apidocjs.com",
    "version": "0.27.1"
  }
});
