define({
  "name": "Lord of the Trips",
  "version": "0.1.0",
  "description": "apiDoc basic example",
  "title": "LOFTS - API documentatiton",
  "url": "https://hephaistos.nathanaelderousseaux.fr/api",
  "sampleUrl": "https://hephaistos.nathanaelderousseaux.fr/api",
  "order": [
    "Login",
    "SignUp",
    "Whoami",
    "GetChallenges",
    "PostChallenge",
    "GetChallenge",
    "PutChallenge",
    "PatchChallenge",
    "DeleteChallenge",
    "GetChallengeImage",
    "PostChallengeImage",
    "GetCrossingPoints",
    "PostCrossingPoint",
    "GetCrossingPoint",
    "PutCrossingPoint",
    "PatchCrossingPoint",
    "DeleteCrossingPoint",
    "GetSegments",
    "PostSegment",
    "GetSegment",
    "PutSegment",
    "PatchSegment",
    "DeleteSegment",
    "GetEvents",
    "PostEvent",
    "GetEvent"
  ],
  "defaultVersion": "0.0.0",
  "apidoc": "0.3.0",
  "generator": {
    "name": "apidoc",
    "time": "2021-04-21T23:56:26.502Z",
    "url": "https://apidocjs.com",
    "version": "0.27.1"
  }
});
